# One PWN at 1 kpc, propagated with energy losses.
injectionmodel = PWN
transportmodel = DiffusionLosses
emin = 10
emax = 1e5
esize = 1000
efficiency = 0.27
pwnp0ms = 30.0
pwnalpha1 = 1.8
pwnalpha2 = 1.8
pwnebreak = 100
