"""Matched H=4 kpc source variations: spectrum shape and excursion statistics."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np
from scipy.special import ndtr

import gryphon_plots as gp
from feature_statistics import excursions, running_indices, summarize
from plot_halos import THRESHOLDS, digest, load_model, survival, validate_parameters as validate_halo

# The H=4 reference is reused, not resimulated or selected by spectral shape.
MODELS = {
    "identical": ("halos_H4", "Identical", "tab:red"),
    "energy": ("variations_energy", "Energy scatter", "tab:blue"),
    "index": ("variations_index", "Index scatter", "tab:green"),
}
LINESTYLES = {"identical": "-", "energy": "--", "index": "-."}


def validate_parameters(params: dict, model: str) -> None:
    if model not in MODELS:
        raise ValueError(f"unknown source-variation model {model}")
    flags = {"varyenergy": "true" if model == "energy" else "false",
             "varyslope": "true" if model == "index" else "false"}
    for key, expected in flags.items():
        if params.get(key) != expected:
            raise ValueError(f"{model}: {key}={params.get(key)!r}, expected {expected!r}")
    if model == "index" and params.get("injslopesigma") != 0.30:
        raise ValueError("index: expected parent injslopesigma=0.30")
    # Check all shared physics against exactly the reference halo prescription.
    validate_halo(dict(params, varyenergy="false", varyslope="false"), 4)


def shared_parameters(params: dict) -> dict:
    """Ignore only the intended variation, inactive width, run name and last seed."""
    return {k: v for k, v in params.items() if k not in
            ("simname", "seed", "varyenergy", "varyslope", "injslopesigma")}


def scaled_spectra(energy, flux):
    """A single scalar per model: E^2.7 J_median = 1 at 1 TeV."""
    energy, flux = np.asarray(energy), np.asarray(flux)
    # Reuse the statistic's validation, without changing the spectra themselves.
    excursions(energy, flux)
    if not np.isclose(energy[0], 1000.):
        raise ValueError("display normalization requires a 1 TeV first bin")
    factor = 1. / (np.median(flux[:, 0]) * energy[0]**2.7)
    return flux * energy**2.7 * factor, float(factor)


def continuous_index_spectrum(energy):
    """Appendix's exact truncated, fixed-energy average, times E^-delta.

    Overall units are irrelevant here. This homogeneous steady-state limit
    illustrates smooth curvature; it is NOT subtracted from the statistics.
    """
    mu, sigma, emin, delta = 2.34, 0.30, 10., 0.36
    energy = np.asarray(energy)
    y = np.log(energy / emin)
    a = (mu - 2.) / sigma
    z = a - sigma * y
    b = np.exp(-0.5 * z*z) / np.sqrt(2 * np.pi) + z * ndtr(z)
    return sigma * b / ndtr(a) * np.exp(-mu*y + 0.5*sigma*sigma*y*y) * (energy / 1e3)**(-delta)


def write_table(path: Path, models: dict) -> None:
    rows = ["% Generated by plot_variations.py; do not edit numerical entries by hand.",
            r"\begin{tabular}{lcccccc}", r"\hline\hline",
            r"Sources & $A_{95}$ & $(\Delta\gamma_{\rm run})_{95}$ & "
            r"$n_{A\geq0.16}$ & $n_{A\geq0.19}$ & "
            r"$n_{\Delta\gamma\geq0.20}$ & $n_{\Delta\gamma\geq0.35}$ \\",
            r"\hline"]
    for name, (_, label, _) in MODELS.items():
        residual, slope = (models[name][key] for key in ("residual", "slope_excursion"))
        counts = [residual["thresholds"][str(t)]["exceedances"] for t in THRESHOLDS[0]]
        counts += [slope["thresholds"][str(t)]["exceedances"] for t in THRESHOLDS[1]]
        rows.append(f"{label} & {100 * residual['percentiles']['95']:.2f}\\% & "
                    f"{slope['percentiles']['95']:.4f} & " +
                    " & ".join(str(n) for n in counts) + r" \\")
    rows.extend((r"\hline\hline", r"\end{tabular}"))
    path.write_text("\n".join(rows) + "\n")


def analyse(proj, number):
    summary = {
        "status": "current-model ensemble; finite Monte Carlo sample, not a data-fit p-value",
        "number_of_realizations_per_model": number,
        "fit_range_gev": [1e3, 1e6], "search_range_gev": [1e4, 1e5],
        "fit_weighting": "equal weight in log flux on a log energy grid",
        "running_slope_window_bins": 5, "running_slope_window_dex": 4 * 3 / 47,
        "intervals": "pointwise exact two-sided 95% Clopper-Pearson; not simultaneous",
        "zero_count_limits": "one-sided 95%: 1 - 0.05**(1/N)",
        "selection": "consecutive seeds; identical source catalogues across injection models",
        "data_bands": "amplitude benchmarks, not confidence intervals for these estimators",
        "display_normalization": "one scalar per model: E^2.7 J_median(1 TeV)=1; no individual rescaling",
        "energy_scatter": {"log10_width_dex": 0.54, "median_energy_erg": 1e50,
                           "mean_to_median": float(np.exp((0.54*np.log(10))**2/2))},
        "index_scatter": {"parent_mean": 2.34, "parent_std": 0.30,
                          "support": "gamma>2; rejection sampling", "energy_above_gev": 10.,
                          "energy_erg": 1e50, "cutoff": "none"},
        "analysis_source_sha256": {name: digest(Path(__file__).with_name(name)) for name in
                                   ("plot_variations.py", "plot_halos.py", "feature_statistics.py")},
        "models": {},
    }
    reference_params = reference_energy = reference_build = None
    models, rows = {}, []
    for name, (run, _, _) in MODELS.items():
        directory = proj.run(run)
        manifest_name = "halos_manifest.json" if name == "identical" else "variations_manifest.json"
        energy, flux, provenance, checksums = load_model(directory, number, manifest_name)
        params = gp.load_params(directory)
        validate_parameters(params, name)
        matched = shared_parameters(params)
        build = {k: provenance[k] for k in ("executable_sha256", "library_sha256")}
        if reference_params is None:
            reference_params, reference_energy, reference_build = matched, energy, build
        elif matched != reference_params or not np.array_equal(energy, reference_energy) or build != reference_build:
            raise ValueError("comparison requires matched shared parameters, energy grids and builds")
        residual, slope = excursions(energy, flux)
        curves, factor = scaled_spectra(energy, flux)
        centres, indices = running_indices(energy, flux)
        # These are diagnostics of the ensemble shape, not a detrending of realizations.
        median_stats = excursions(energy, np.median(flux, axis=0))
        result = {
            "seeds": list(range(number)), "parameters": {k: v for k, v in params.items() if k != "seed"},
            "provenance": provenance, "flux_sha256_by_seed": checksums,
            "residual": summarize(residual, THRESHOLDS[0]),
            "slope_excursion": summarize(slope, THRESHOLDS[1]),
            "median_spectrum_statistics": {"residual": float(median_stats[0][0]),
                                           "slope_excursion": float(median_stats[1][0])},
            "display_flux_factor": factor,
            "energy_gev": energy.tolist(),
            "flux_percentiles": {str(q): np.percentile(flux, q, axis=0).tolist() for q in (5, 50, 95)},
            "running_index_energy_gev": centres.tolist(),
            "running_index_percentiles": {str(q): np.percentile(indices, q, axis=0).tolist() for q in (5, 50, 95)},
            "sample_size_checks": {},
        }
        for n in sorted({max(1, number//4), max(1, number//2), number}):
            result["sample_size_checks"][str(n)] = {
                "residual": summarize(residual[:n], THRESHOLDS[0]),
                "slope_excursion": summarize(slope[:n], THRESHOLDS[1]),
            }
        summary["models"][name] = result
        models[name] = (energy, curves, centres, indices, residual, slope)
        rows.extend((name, seed, a, d) for seed, (a, d) in enumerate(zip(residual, slope)))
    a, d = excursions(reference_energy, continuous_index_spectrum(reference_energy))
    summary["continuous_index_limit"] = {
        "assumption": "homogeneous steady-state J proportional to mean(Q)/D; Appendix truncated fixed-energy mean",
        "residual": float(a[0]), "slope_excursion": float(d[0]),
        "subtracted_from_realizations": False,
    }
    return models, summary, rows


def plot_spectra(models, number, output):
    import matplotlib.pyplot as plt
    fig, axes = plt.subplots(1, 2, figsize=(16, 7.7))
    for name, (energy, curves, centres, indices, _, _) in models.items():
        _, label, color = MODELS[name]
        for ax, x, values in ((axes[0], energy, curves), (axes[1], centres, indices)):
            low, median, high = np.percentile(values, [5, 50, 95], axis=0)
            ax.fill_between(x, low, high, color=color, alpha=0.16, linewidth=0)
            ax.plot(x, median, color=color, label=label, linewidth=2.8,
                    linestyle=LINESTYLES[name])
    for ax in axes:
        ax.set(xscale="log", xlim=(1e3, 1e6), xlabel=r"$E$ [GeV]")
        ax.grid(False, which="both")
        ax.tick_params(labelsize=23)
    axes[0].set_ylabel(r"Normalized $E^{2.7}J(E)$")
    axes[1].set_ylabel(r"Running index $\gamma_{\rm run}$")
    axes[0].legend(loc="upper left", fontsize=20)
    axes[1].text(0.04, 0.05, r"$H=4$ kpc, Xie" + "\n" + f"{number:,} realizations / model" +
                 "\nMedian and central 90\\%", transform=axes[1].transAxes,
                 ha="left", va="bottom", fontsize=19)
    for extension in ("pdf", "png"):
        fig.savefig(output / f"gryphon_variations_spectra.{extension}", bbox_inches="tight", dpi=140)
    plt.close(fig)


def plot_statistics(models, number, output):
    import matplotlib.pyplot as plt
    fig, axes = plt.subplots(1, 2, figsize=(16, 7.7))
    xmax = max(0.8, 1.1 * max(float(v.max()) for *_, a, d in models.values() for v in (a, d)))
    for name, (*_, residual, slope) in models.items():
        _, label, color = MODELS[name]
        for ax, values in zip(axes, (residual, slope)):
            x = np.unique(np.r_[1e-3, values[values >= 1e-3], xmax, *THRESHOLDS[0], *THRESHOLDS[1]])
            empirical, lower, upper = survival(values, x)
            ax.fill_between(x, np.maximum(lower, 1e-8), upper, step="pre", color=color,
                            alpha=0.12, linewidth=0)
            ax.step(x, empirical, where="pre", color=color, label=label,
                    linestyle=LINESTYLES[name])
    for ax, band, xlabel in zip(axes, THRESHOLDS,
                               (r"Maximum residual $A$", r"Running-slope excursion $\Delta\gamma_{\rm run}$")):
        ax.axvspan(*band, color="0.65", alpha=0.30, zorder=0, label="Data range")
        ax.axhline(1./number, color="0.4", linestyle=":", linewidth=1.2, zorder=1)
        ax.set(xscale="log", yscale="log", xlim=(1e-3, xmax), ylim=(max(1e-7, 0.25/number), 1.05),
               xlabel=xlabel, ylabel=r"Survival probability $P(\geq x)$")
        ax.grid(False, which="both")
        ax.tick_params(labelsize=23)
    axes[0].legend(loc="lower left", fontsize=19, frameon=True,
                   facecolor="white", edgecolor="none", framealpha=1.)
    axes[1].text(0.04, 0.05, f"{number:,} realizations / model" + "\n" + r"$H=4$ kpc, Xie" +
                 "\n" + r"$10<E<100$ TeV", transform=axes[1].transAxes,
                 ha="left", va="bottom", fontsize=18,
                 bbox=dict(facecolor="white", edgecolor="none", pad=3))
    for extension in ("pdf", "png"):
        fig.savefig(output / f"gryphon_variations_statistics.{extension}", bbox_inches="tight", dpi=140)
    plt.close(fig)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--seeds", type=int, default=10000)
    parser.add_argument("--output", type=Path, help="separate preview directory; default project figures")
    args = parser.parse_args()
    gp.style.use()
    proj = gp.project()
    output = args.output or proj.figures
    output.mkdir(parents=True, exist_ok=True)
    models, summary, rows = analyse(proj, args.seeds)
    plot_spectra(models, args.seeds, output)
    plot_statistics(models, args.seeds, output)
    (output / "variations_summary.json").write_text(json.dumps(summary, indent=2) + "\n")
    with (output / "variations_statistics.txt").open("w") as out:
        out.write("# model seed residual slope_excursion\n")
        for name, seed, a, d in rows:
            out.write(f"{name} {seed} {a:.10e} {d:.10e}\n")
    write_table(output / "variations_table.tex", summary["models"])
    print(json.dumps({name: {key: data[key] for key in ("residual", "slope_excursion", "median_spectrum_statistics")}
                      for name, data in summary["models"].items()}, indent=2))


if __name__ == "__main__":
    main()
