"""Cutoff-free identical-source halo comparison; ideal-spectrum diagnostics."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

import numpy as np

import gryphon_plots as gp
from feature_statistics import binomial_interval, excursions, summarize
from figure2_common import HALOS as HALO_STYLES

HALOS = (2, 4, 8)
THRESHOLDS = ((0.16, 0.19), (0.20, 0.35))


def digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def validate_parameters(params: dict, halo: int) -> None:
    required = {
        "hkpc": halo, "spiralmodel": "Xie2024", "transportmodel": "PureDiffusion",
        "injectionmodel": "GalacticRandom", "pid": "H", "d0h": 0.42,
        "e0": 1000., "delta": 0.36, "ddelta": -1., "snrateyr": 0.02,
        "maxtimemyr": 100., "timestep": 1., "emin": 1000., "emax": 1e6,
        "esize": 48., "injslope": 2.34, "injemax": 0., "efficiency": 0.1,
        "varyenergy": "false", "varyslope": "false", "syntheticassociations": "false",
        "rgkpc": 20., "sunkpc": 8.5, "discsizepc": 50.,
    }
    for key, expected in required.items():
        if params.get(key) != expected:
            raise ValueError(f"H={halo}: {key}={params.get(key)!r}, expected {expected!r}")


def load_model(directory: Path, number: int, manifest_name: str = "halos_manifest.json",
               extra_stems: tuple[str, ...] = (), *, grid=(1e3, 1e6, 48)):
    """Read only the requested, unselected prefix of verified completed seeds."""
    if number < 1:
        raise ValueError("number of realizations must be positive")
    manifest = json.loads((directory / manifest_name).read_text())
    if hashlib.sha256(manifest["config_text"].encode()).hexdigest() != manifest["config_sha256"]:
        raise ValueError(f"{directory}: config manifest checksum mismatch")
    energy, spectra, checksums = None, [], []
    for seed in range(number):
        marker = directory / f"complete_{seed:06d}.json"
        flux_file = directory / f"flux_{seed:06d}.txt"
        if not marker.exists() or not flux_file.exists():
            raise ValueError(f"{directory}: seed {seed} is not complete")
        checksum = digest(flux_file)
        expected_hashes = {"flux_sha256": checksum}
        for stem in extra_stems:
            extra = directory / f"{stem}_{seed:06d}.txt"
            if not extra.exists():
                raise ValueError(f"{directory}: seed {seed} missing {stem}")
            expected_hashes[f"{stem}_sha256"] = digest(extra)
        if json.loads(marker.read_text()) != expected_hashes:
            raise ValueError(f"{directory}: seed {seed} failed checksum verification")
        table = gp.load(flux_file)
        if int(table.meta["seed"]) != seed or table.meta["simname"] != directory.name:
            raise ValueError(f"{directory}: seed/run header mismatch")
        if energy is None:
            energy = table["E"]
        elif not np.array_equal(table["E"], energy):
            raise ValueError(f"{directory}: inconsistent energy grids")
        spectra.append(table["I"])
        checksums.append(checksum)
    if len(energy) != grid[2] or not np.allclose(energy, np.geomspace(*grid), rtol=1e-8):
        raise ValueError(f"{directory}: incorrect energy grid")
    return energy, np.stack(spectra), manifest, checksums


def survival(values: np.ndarray, thresholds: np.ndarray):
    values = np.asarray(values)
    counts = len(values) - np.searchsorted(np.sort(values), thresholds, side="left")
    lower, upper = binomial_interval(counts, len(values))
    # On logarithmic axes zero counts are absent, never assigned a fake floor.
    empirical = np.where(counts > 0, counts / len(values), np.nan)
    return empirical, lower, upper


def write_table(path: Path, models: dict) -> None:
    """Small manuscript table; all numerical entries derive from verified runs."""
    # Keep the complete alignment in one input file: REVTeX's input hooks can
    # otherwise insert material between the last row and a following hline.
    rows = ["% Generated by plot_halos.py; do not edit numerical entries by hand.",
            r"\begin{tabular}{ccccccc}", r"\hline\hline",
            r"$H$ [kpc] & $A_{95}$ & $(\Delta\gamma_{\rm run})_{95}$ & "
            r"$n_{A\geq0.16}$ & $n_{A\geq0.19}$ & "
            r"$n_{\Delta\gamma\geq0.20}$ & $n_{\Delta\gamma\geq0.35}$ \\",
            r"\hline"]
    for halo in HALOS:
        data = models[str(halo)]
        residual, slope = data["residual"], data["slope_excursion"]
        counts = [residual["thresholds"][str(t)]["exceedances"] for t in THRESHOLDS[0]]
        counts += [slope["thresholds"][str(t)]["exceedances"] for t in THRESHOLDS[1]]
        rows.append(f"{halo} & {100 * residual['percentiles']['95']:.2f}\\% & "
                    f"{slope['percentiles']['95']:.4f} & " +
                    " & ".join(str(count) for count in counts) + r" \\")
    rows.extend((r"\hline\hline", r"\end{tabular}"))
    path.write_text("\n".join(rows) + "\n")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--seeds", type=int, default=10000,
                        help="use the unselected prefix 0,...,N-1 in every model")
    args = parser.parse_args()
    gp.style.use()
    import matplotlib.pyplot as plt

    proj = gp.project()
    fig, axes = plt.subplots(1, 2, figsize=(16, 7.7))
    summary = {
        "status": "current-model ensemble; finite Monte Carlo sample, not a data-fit p-value",
        "number_of_realizations_per_halo": args.seeds,
        "fit_range_gev": [1e3, 1e6], "fit_weighting": "equal weight in log flux on a log energy grid",
        "search_range_gev": [1e4, 1e5], "running_slope_window_bins": 5,
        "running_slope_window_dex": 4 * 3 / 47,
        "intervals": "pointwise exact two-sided 95% Clopper-Pearson; not simultaneous",
        "zero_count_limits": "one-sided 95%: 1 - 0.05**(1/N)",
        "selection": "consecutive unselected seeds; same catalogues at all halo heights",
        "data_bands": "amplitude benchmarks, not confidence intervals for these estimators",
        "analysis_source_sha256": {
            name: digest(Path(__file__).with_name(name))
            for name in ("plot_halos.py", "feature_statistics.py")
        },
        "models": {},
    }
    reference_params = reference_energy = reference_build = None
    rows, plot_values = [], []
    for halo in HALOS:
        color = dict(HALO_STYLES)[halo]
        directory = proj.run(f"halos_H{halo}")
        energy, flux, provenance, checksums = load_model(directory, args.seeds)
        params = gp.load_params(directory)
        validate_parameters(params, halo)
        # params.ini stores the last seed executed, not the seed of every file.
        params = {key: value for key, value in params.items() if key != "seed"}
        matched = {key: value for key, value in params.items() if key not in ("simname", "hkpc")}
        build = {key: provenance[key] for key in ("executable_sha256", "library_sha256")}
        if reference_params is None:
            reference_params, reference_energy, reference_build = matched, energy, build
        elif matched != reference_params or not np.array_equal(energy, reference_energy) or build != reference_build:
            raise ValueError("halo comparison requires matched parameters, energy grids and builds")
        residual, slope = excursions(energy, flux)
        result = {
            "seeds": list(range(args.seeds)), "parameters": params,
            "provenance": provenance, "flux_sha256_by_seed": checksums,
            "residual": summarize(residual, THRESHOLDS[0]),
            "slope_excursion": summarize(slope, THRESHOLDS[1]),
            "sample_size_checks": {},
        }
        # Fixed prefixes, not selected subsamples: diagnose bulk-quantile stability.
        for n in sorted({max(1, args.seeds // 4), max(1, args.seeds // 2), args.seeds}):
            result["sample_size_checks"][str(n)] = {
                "residual": summarize(residual[:n], THRESHOLDS[0]),
                "slope_excursion": summarize(slope[:n], THRESHOLDS[1]),
            }
        summary["models"][str(halo)] = result
        rows.extend((halo, seed, a, d) for seed, (a, d) in enumerate(zip(residual, slope)))
        plot_values.append((halo, color, residual, slope))
    xmax = max(0.8, 1.1 * max(float(v.max()) for _, _, a, d in plot_values for v in (a, d)))
    for halo, color, residual, slope in plot_values:
        for ax, values in zip(axes, (residual, slope)):
            # Include every observed order statistic and benchmark threshold.
            x = np.unique(np.r_[1e-3, values[values >= 1e-3],
                                xmax, *THRESHOLDS[0], *THRESHOLDS[1]])
            empirical, lower, upper = survival(values, x)
            ax.fill_between(x, np.maximum(lower, 1e-8), upper, step="pre",
                            color=color, alpha=0.12, linewidth=0)
            ax.step(x, empirical, where="pre", color=color, label=rf"$H={halo}$ kpc")
    for ax, band, xlabel in zip(axes, THRESHOLDS,
                               (r"Maximum residual $A$", r"Running-slope excursion $\Delta\gamma_{\rm run}$")):
        ax.axvspan(*band, color="0.65", alpha=0.30, zorder=0, label="Data range")
        ax.axhline(1. / args.seeds, color="0.4", linestyle=":", linewidth=1.2, zorder=1)
        ax.set(xscale="log", yscale="log", xlim=(1e-3, xmax),
               ylim=(max(1e-7, 0.25 / args.seeds), 1.05), xlabel=xlabel,
               ylabel=r"Survival probability $P(\geq x)$")
        ax.grid(False, which="both")
        ax.tick_params(labelsize=23)
    axes[0].legend(fontsize=19, loc="upper right")
    axes[1].text(0.97, 0.95, f"{args.seeds:,} realizations / halo" + "\n" +
                 "Identical sources, Xie\n" + r"$10<E<100$ TeV",
                 transform=axes[1].transAxes, va="top", ha="right", fontsize=18)
    proj.figures.mkdir(parents=True, exist_ok=True)
    fig.savefig(proj.figures / "gryphon_halo_statistics.pdf", bbox_inches="tight")
    fig.savefig(proj.figures / "gryphon_halo_statistics.png", dpi=140, bbox_inches="tight")
    plt.close(fig)
    (proj.figures / "halos_summary.json").write_text(json.dumps(summary, indent=2) + "\n")
    with (proj.figures / "halos_statistics.txt").open("w") as out:
        out.write("# halo_kpc seed residual slope_excursion\n")
        for halo, seed, residual, slope in rows:
            out.write(f"{halo} {seed} {residual:.10e} {slope:.10e}\n")
    write_table(proj.figures / "halos_table.tex", summary["models"])
    print(json.dumps({halo: {key: data[key] for key in ("residual", "slope_excursion")}
                      for halo, data in summary["models"].items()}, indent=2))


if __name__ == "__main__":
    main()
